dataset_params:
  # im_path: 'dataset/data/train/images'
  # the data is contained in the 'data' folder in the root directory. there should be another 'mean_std.npz' file in the same folder with mean ans std values
  # data_dir: '../data/Re500_fkx4fky4_r0.1_b20/NoSGS/NX64/dt0.0005_IC1/'
  # data_dir: 'Re500_fkx4fky4_r0.1_b20/2D_64_spectral_dt0.02_noise_2500/' # training on emulator data
  data_dir: '2D_64_spectral_dt0.02_noise_2500/'

  file_range: [5000, 7500]
  downsample_factor: 1
  downsample_procedure: 'spectral' # spectral physical
  normalize: !!bool True

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model_params:
  im_channels : 2
  im_size : 64
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

train_params:
  task_name: '2D_64_spectral_dt0.02_noise_2500'
  # task_name: 'test'
  batch_size: 16
  num_epochs: 200
  lr: 0.0001
  loss: 'noise' # sample noise
  ckpt_name: 'ddpm_ckpt.pth'
  best_ckpt_name: 'best_ddpm_ckpt.pth'

# For Testing (Post training)
test_params:
  batch_size : 16 # Testing data batch size
  num_test_batch : 100000 # number of samples = test_batch * num_test_batch
  save_image: !!bool False # Saves snapshots of emulated data
  save_data: !!bool True # Saved emulated data
