
# Directory for the emulator, truth, train data
system_params:
  system: 'Re500_fkx4fky4_r0.1_b20'
  Ngrid: 64

# root_dir: "/home/exouser/karan/2DTurbDiffusion_cnditional/results/ddpm/"
root_dir: "/home/exouser/karan/2DTurbDiffusion_cnditional/results/1CDM_s3_Oaw_lrC3e4"
# root_dir: '/home/exouser/karan/data/Re500_fkx4fky4_r0.1_b20/NoSGS/NX64/dt0.0005_IC1' # provide IC num below
save_dir:   # If empty same as root_dir
# save_dir: 'resUlts/train_step3_10000_40000'

long_analysis_params:

# For Truth
  data_type: 'emulator' # 'train', 'emulator', 'truth'
  file_range: [0, 800]

  # Only used for train and truth
  step_size: 3 # Use every nth step for analysis (e.g., 3 means every 3rd step)
  IC_num: [1] # Only used for truth/train - it will analyze single or multiple ICs

  # Only used for emulator data when conditional=True
  ensemble_name: '1_0' #  - It will only analyze the data of ingle ensemble in apartocular folder.

  temporal_mean: !!bool True
  zonal_mean: !!bool True
  spectra: !!bool True
  zonal_eof_pc: !!bool True
  eof_ncomp: 3
  PC_autocorr_nlags: 300 # Number of lags (Emulator timesteps) for autocorrelation  # Ensure training/truth data is longer than this (3 times?)

  div: !!bool True
  energy: !!bool True
  enstrophy: !!bool True

  extreme: !!bool True
  extreme_block: !!bool True # Check if temporal mean is saved, if not it will compute it, and use for anamoly calculation
  extreme_anomaly: !!bool False # This requires calclation of temporal_mean
  extreme_anomaly_block: !!bool False 
  num_remove_boundary: 0 # Check for bugs? Number of boundary points to remove for extreme analysis 
  
  zonal_U: !!bool True # Save zonal mean U at each time step
  zonal_V: !!bool True # Save zonal mean V at each time step
  zonal_Omega: !!bool True # Save zonal mean Omega at each time step

  PDF_U: !!bool True # This may need large memory to compute
  PDF_V: !!bool True # This may need large memory to compute
  PDF_Omega: !!bool True # This may need large memory to compute
  PDF_data_ratio: 1 # Ratio of data to use for PDF analysis (0.1 means 10% of the data will be used)
  
  video: !!bool False
  video_length: 300