
# Directory for the emulator, truth, train data
system_params:
  system: 'Re500_fkx4fky4_r0.1_b20'
  Ngrid: 64

# root_dir: "/home/exouser/karan/2DTurbDiffusion_cnditional/results/ddpm/"
root_dir: "/home/exouser/karan/2DTurbDiffusion_cnditional/results/CDM_s3_Oaw_lrC3e4_2500"
# root_dir: '/home/exouser/karan/data/Re500_fkx4fky4_r0.1_b20/NoSGS/NX64/dt0.0005_IC1' # provide IC num below
save_dir:   # If empty same as root_dir
# save_dir: 'results/train_step3_400000_407500'

long_analysis_params:

# For Truth
  data_type: 'emulator' # 'train', 'emulator', 'truth'
  file_range: [0, 25000]

  # Only used for train and truth
  step_size: 3 # Use every nth step for analysis (e.g., 3 means every 3rd step)
  IC_num: [1] # Only used for truth/train - it will analyze single or multiple ICs

  # Only used for emulator data when conditional=True
  ensemble_name: '1_0' #  all: analyze data in all folder, <ensemble_name>: It will only analyze the data of single ensemble in a particular folder.

  temporal_mean: !!bool True
  zonal_mean: !!bool True
  spectra: !!bool True
  zonal_eof_pc: !!bool True # Needs temporal_mean and zonal_mean to be True
  eof_ncomp: 3
  PC_autocorr_nlags: 300 # Number of lags (Emulator timesteps) for autocorrelation  # Ensure training/truth data is longer than this (3 times?)

  div: !!bool True
  energy: !!bool True
  enstrophy: !!bool True

  extreme: !!bool True
  extreme_block: !!bool True # Check if temporal mean is saved, if not it will compute it, and use for anamoly calculation
  extreme_anomaly: !!bool True # This requires calculation of temporal_mean
  extreme_anomaly_block: !!bool True
  num_remove_boundary: 0 # Check for bugs? Number of boundary points to remove for extreme analysis

  zonal_U: !!bool True # Save zonal mean U at each time step
  zonal_V: !!bool True # Save zonal mean V at each time step
  zonal_Omega: !!bool True # Save zonal mean Omega at each time step

  PDF_U: !!bool False # This may need large memory to compute
  PDF_V: !!bool False # This may need large memory to compute
  PDF_Omega: !!bool False # This may need large memory to compute
  PDF_data_ratio: 1 # Ratio of data to use for PDF analysis (0.1 means 10% of the data will be used)


# only needed for conditional diffusion model
short_analysis_params:
  analysis_length: 100 # Length of the analysis data (number of time steps)
  analysis_num_ensembles: 10 # Number of ensembles to analyze
  ensemble_dir_list : 'all' # all ['1_0', '2_0'] # List of ensemble directories to analyze
  rmse: !!bool False
  acc: !!bool False

  spectra: !!bool False
  spectra_lead_times: [1, 2, 3, 4, 5] # Lead times for spectra analysis

  video: !!bool False
  video_length: 300